networks:
   clientes-network:
      name: clientes-network
services:
   rabbitmq:
      image: rabbitmq:management
      ports:
         - "5672:5672"
         - "15672:15672"
      networks:
         - clientes-network
   mysql-db:
      image: mysql
      restart: always
      container_name: mysql-db
      environment:
         MYSQL_ROOT_PASSWORD: password
         MYSQL_DATABASE: clientesdb
      networks:
         - clientes-network  
      ports:
         - 3306:3306
   phpmyadmin:
      depends_on:
         - mysql-db
      image: phpmyadmin
      restart: always
      container_name: php-my-admin
      environment:        
         PMA_HOST: mysql-db
      networks:
         - clientes-network  
      ports:
         - 8090:80
   clientes:
      build:
         context: ./docker-clientes
      depends_on:
         - mysql-db
         - rabbitmq
      container_name: clientes
      environment:
         SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/clientesdb
         RABBITMQ_HOST: rabbitmq
         RABBITMQ_PORT: 5672
         RABBITMQ_USER: guest
         RABBITMQ_PASSWORD: guest
         MYSQL_SERVER_IP: mysql-db
         MYSQL_SERVER_PORT: 3306
         MYSQL_USER: root
         MYSQL_PASSWORD: password
      links:
         - mysql-db
         - rabbitmq
      networks:
         - clientes-network  
      ports:
         - 8081:8081
      restart: always
         
   movimientos:
      build:
         context: ./docker-movimientos
      depends_on:
         - mysql-db
         - rabbitmq
      container_name: movimientos
      environment:
         RABBITMQ_HOST: rabbitmq
         RABBITMQ_PORT: 5672
         RABBITMQ_USER: guest
         RABBITMQ_PASSWORD: guest
         REST_CLIENTE_URL: http://clientes:8081/clientes
         MYSQL_SERVER_IP: mysql-db
         MYSQL_SERVER_PORT: 3306
         MYSQL_USER: root
         MYSQL_PASSWORD: password
         SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/cuenta_movimiento
         
      links:
         - mysql-db
         - rabbitmq
      networks:
         - clientes-network  
      ports:
         - 8082:8082
